### ISSUE TITLE
Add support for OAuth token usage

### ISSUE THREAD

**Issue by linkmauve** [btotharye/mattermost-wrapper-v4#3]
This package currently requires a password for login, it should instead allow for OAuth token to be provided.

See also https://docs.mattermost.com/developer/personal-access-tokens.html

**Comment by btotharye** [comment]
agreed I need to start back on this, will look at it

**Comment by btotharye** [comment]
Sorry been gone a while on this but coming back to it, going to look at the new bot accounts option this coming week

**Comment by btotharye** [comment]
@linkmauve as of version `2.2` you can now pass in a token value to the init and use it.  I added it for bot accounts but should also work for personal access tokens and such.

**Comment by linkmauve** [comment]
Thanks, but I don’t work at a company using Mattermost anymore.  I hope it’ll be useful for someone else then, you can close this issue if you are confident it’s been fixed. :)
